spring:
  profiles:
    active: local
--- # local

server:
  servlet:
    register-default-servlet: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    activate:
      on-profile: local
  application:
    name: myomyo
  datasource:
    hikari:
      master:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        username: postgres
        password: army0101
        maximum-pool-size: 20


--- # dev

server:
  servlet:
    register-default-servlet: true


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    activate:
      on-profile: dev
  application:
    name: myomyo
  datasource:
    hikari:
      master:
        jdbc-url: jdbc:log4jdbc:postgresql://myomyo-db.czz3ntuyvxak.ap-northeast-2.rds.amazonaws.com:5432/myomyodb
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        username: postgres
        password: sudasuda25
        maximum-pool-size: 20

